// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";
import type { Db, MongoClient } from "npm:mongodb";

export const Engine = new SyncConcept();

import { testDb } from "@utils/database.ts";

import AdaptiveScheduleConcept from "./AdaptiveSchedule/AdaptiveSchedule.ts";
import AuthConcept from "./Auth/Auth.ts";
import ScheduleTimeConcept from "./ScheduleTime/ScheduleTime.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import RoutineLogConcept from "./RoutineLog/RoutineLog.ts";
import TaskCatalogConcept from "./TaskCatalog/TaskCatalog.ts";

export type { default as AdaptiveScheduleConcept } from "./AdaptiveSchedule/AdaptiveSchedule.ts";
export type { default as AuthConcept } from "./Auth/Auth.ts";
export type { default as ScheduleTimeConcept } from "./ScheduleTime/ScheduleTime.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as RoutineLogConcept } from "./RoutineLog/RoutineLog.ts";
export type { default as TaskCatalogConcept } from "./TaskCatalog/TaskCatalog.ts";

// Database and client - will be initialized by init()
export let db: Db = null as any;
export let client: MongoClient = null as any;

export let AdaptiveSchedule: any = null as any;
export let Auth: any = null as any;
export let ScheduleTime: any = null as any;
export let Requesting: any = null as any;
export let RoutineLog: any = null as any;
export let TaskCatalog: any = null as any;

// Initialization flag
let initialized = false;

// Initialize all concepts - MUST be called before using any concepts
export async function init() {
  if (initialized) {
    console.log("⚠️ Concepts already initialized, skipping...");
    return;
  }

  try {
    console.log("🔄 Initializing database connection...");
    const [dbInstance, clientInstance] = await testDb();
    db = dbInstance;
    client = clientInstance;
    console.log("✅ Database connection successful");

    console.log("🔄 Initializing concepts...");
    AdaptiveSchedule = Engine.instrumentConcept(new AdaptiveScheduleConcept(db));
    Auth = Engine.instrumentConcept(new AuthConcept(db));
    ScheduleTime = Engine.instrumentConcept(new ScheduleTimeConcept(db));
    Requesting = Engine.instrumentConcept(new RequestingConcept(db));
    RoutineLog = Engine.instrumentConcept(new RoutineLogConcept(db));
    TaskCatalog = Engine.instrumentConcept(new TaskCatalogConcept(db));

    initialized = true;
    console.log("✅ All concepts initialized successfully");
  } catch (error) {
    console.error("❌ Failed to initialize concepts:", error);
    throw new Error(`Concept initialization failed: ${error instanceof Error ? error.message : String(error)}`);
  }
}

