// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";
import { Db, MongoClient } from "npm:mongodb";

export const Engine = new SyncConcept();

import { testDb } from "@utils/database.ts";

import RequestingConcept from "./Requesting/RequestingConcept.ts";

export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";

// Database and client will be initialized by initializeConcepts()
export let db: Db;
export let client: MongoClient;

// Concept instances - initialized by initializeConcepts()
export let Requesting: ReturnType<typeof Engine.instrumentConcept>;

// Initialize all concepts with test database connection
export async function initializeConcepts() {
  const [dbInstance, clientInstance] = await testDb();
  db = dbInstance;
  client = clientInstance;

  Requesting = Engine.instrumentConcept(new RequestingConcept(db));
}
